name: Electron Typescript Linter

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint TS/ES
      run: pnpm run lint
